from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

NAVY = colors.HexColor("#1B3A5C")
SLATE = colors.HexColor("#4A5A6A")
LIGHT_BG = colors.HexColor("#F2F5F8")
RULE = colors.HexColor("#C9D4DE")

# Ordered to match the NDISProgressNote schema
SECTION_ORDER = [
    ("Subjective", "subjective"),
    ("Objective", "objective"),
    ("Assessment", "assessment"),
    ("Plan", "plan"),
    ("Participant Voice", "participant_voice"),
    ("Support Type Provided", "support_type"),
    ("Risks / Incidents", "risks_incidents"),
]


def _build_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        "ClinicTitle", parent=styles["Title"],
        fontName="Helvetica-Bold", fontSize=18, textColor=NAVY,
        spaceAfter=2, alignment=0,
    ))
    styles.add(ParagraphStyle(
        "DocSubtitle", parent=styles["Normal"],
        fontName="Helvetica", fontSize=10, textColor=SLATE,
        spaceAfter=0,
    ))
    styles.add(ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"],
        fontName="Helvetica-Bold", fontSize=12, textColor=colors.white,
        spaceBefore=0, spaceAfter=0, leading=16,
    ))
    styles.add(ParagraphStyle(
        "SectionBody", parent=styles["BodyText"],
        fontName="Helvetica", fontSize=10.5, textColor=colors.HexColor("#222222"),
        leading=15, spaceBefore=8, spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        "MetaLabel", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=9, textColor=SLATE,
    ))
    styles.add(ParagraphStyle(
        "MetaValue", parent=styles["Normal"],
        fontName="Helvetica", fontSize=9, textColor=colors.HexColor("#222222"),
    ))
    styles.add(ParagraphStyle(
        "GoalItem", parent=styles["Normal"],
        fontName="Helvetica", fontSize=10, textColor=colors.HexColor("#222222"),
        leading=14, leftIndent=10, spaceAfter=2,
    ))
    return styles


def _header_footer(canvas, doc):
    canvas.saveState()
    width, height = letter

    canvas.setStrokeColor(RULE)
    canvas.setLineWidth(0.5)
    canvas.line(0.75 * inch, 0.65 * inch, width - 0.75 * inch, 0.65 * inch)

    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(SLATE)
    canvas.drawString(
        0.75 * inch, 0.48 * inch,
        "Generated by AI documentation assistant \u2014 for support worker/coordinator review prior to submission."
    )
    canvas.drawRightString(width - 0.75 * inch, 0.48 * inch, f"Page {doc.page}")

    canvas.restoreState()


def _consent_display(value) -> str:
    if value is True:
        return "Yes"
    if value is False:
        return "No"
    return "Not documented"


def soap_to_pdf(
    soap_data,
    output_path: Path,
    participant_name: str = "Participant",
    support_worker_name: str = "Not specified",
    encounter_date: str | None = None,
) -> Path:
    """
    Render an NDIS Progress Note as a professionally formatted PDF.

    soap_data: either an NDISProgressNote-like object with the schema's
               attributes, or a dict with those keys.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(exist_ok=True, parents=True)

    # Normalize input to a plain dict
    if isinstance(soap_data, dict):
        data = soap_data
    else:
        data = {
            "subjective": getattr(soap_data, "subjective", ""),
            "objective": getattr(soap_data, "objective", ""),
            "assessment": getattr(soap_data, "assessment", ""),
            "plan": getattr(soap_data, "plan", ""),
            "linked_goals": getattr(soap_data, "linked_goals", []),
            "support_type": getattr(soap_data, "support_type", ""),
            "participant_voice": getattr(soap_data, "participant_voice", ""),
            "risks_incidents": getattr(soap_data, "risks_incidents", ""),
            "consent_noted": getattr(soap_data, "consent_noted", None),
        }

    encounter_date = encounter_date or datetime.now().strftime("%B %d, %Y")
    generated_ts = datetime.now().strftime("%B %d, %Y %I:%M %p")

    styles = _build_styles()
    story = []

    story.append(Paragraph("NDIS Progress Note", styles["ClinicTitle"]))
    story.append(Paragraph("Participant Support Documentation Summary", styles["DocSubtitle"]))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.2, color=NAVY, spaceAfter=10))

    consent_text = _consent_display(data.get("consent_noted"))

    meta_rows = [
        [Paragraph("Participant", styles["MetaLabel"]), Paragraph(participant_name, styles["MetaValue"]),
         Paragraph("Date of Support", styles["MetaLabel"]), Paragraph(encounter_date, styles["MetaValue"])],
        [Paragraph("Support Worker", styles["MetaLabel"]), Paragraph(support_worker_name, styles["MetaValue"]),
         Paragraph("Document Generated", styles["MetaLabel"]), Paragraph(generated_ts, styles["MetaValue"])],
        [Paragraph("Consent Noted", styles["MetaLabel"]), Paragraph(consent_text, styles["MetaValue"]),
         Paragraph("", styles["MetaLabel"]), Paragraph("", styles["MetaValue"])],
    ]
    meta_table = Table(meta_rows, colWidths=[1.2 * inch, 2.1 * inch, 1.3 * inch, 1.9 * inch])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, RULE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, RULE),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 18))

    for heading, key in SECTION_ORDER:
        raw_value = data.get(key)
        text = (raw_value or "Not documented.")
        if isinstance(text, str):
            text = text.strip() or "Not documented."

        header_table = Table(
            [[Paragraph(heading.upper(), styles["SectionHeading"])]],
            colWidths=[6.5 * inch],
        )
        header_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), NAVY),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(header_table)

        body_para = Paragraph(text.replace("\n", "<br/>"), styles["SectionBody"])
        body_table = Table([[body_para]], colWidths=[6.5 * inch])
        body_table.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.5, RULE),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(body_table)
        story.append(Spacer(1, 12))

    # Linked NDIS Goals — rendered as a bulleted list since it's an array field
    goals = data.get("linked_goals") or []
    header_table = Table(
        [[Paragraph("LINKED NDIS GOALS", styles["SectionHeading"])]],
        colWidths=[6.5 * inch],
    )
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(header_table)

    if goals:
        goal_paras = [Paragraph(f"\u2022 {g}", styles["GoalItem"]) for g in goals]
        body_content = goal_paras
    else:
        body_content = [Paragraph("Not documented.", styles["SectionBody"])]

    body_table = Table([[c] for c in body_content], colWidths=[6.5 * inch])
    body_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, RULE),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(body_table)
    story.append(Spacer(1, 12))

    document = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.85 * inch,
        title="NDIS Progress Note",
    )
    document.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return output_path